### ISSUE TITLE
Ability to create some ViewClass objects by the user and pass it on RV init

### ISSUE THREAD

**Issue by ghost** [kivy-garden/garden.recycleview#14]
If we have a little amount of things to scroll, we should be able to create those views 'permanently' and f.e. pass it in form of ReferenceListProperty or ListProperty on RV init. It should increase the RV performance, especially on low-end Android devices.

**Comment by tito** [comment]
What do you mean by permanently?

Performance is very subjective here, and the widget internal are already more optimized than most Kivy widget. And please note that creating more widget than necessary cost more time at creation and use more memory than reuse the current one ^^

**Comment by ghost** [comment]
For example:

If you have a wallpaper app for Android with 10-12 wallpaper's thumbs and you run it on low-end Android phone (Galaxy Ace II), using the ScrollView with thumbs added as standard widgets to the SV seems to be more responsive and fluid on first scroll than using RV with data list. After few scrolls it is OK, but the first laggy scroll with RV gives the bad user experience and user opinion is bad from the start. So I bet that preloading 10-12 widgets references could be better from the scrolling performance point of view, than using dynamic nature of RV. Maybe app init will be 0.5-1 second longer, but the smooth scrolling will be give much more value for the user.

Just wondering ;)

**Comment by tito** [comment]
Yes, but on that specific case, i would say it works for 10/12, but 20, you'll still have the issue. Image loading is your real bet here, and to prevent any lag, you want preloading.

The whole goal of RV is it's dynamic loading. If you want static widget, what not using gridlayout + scrollview? Because it look like RV is too dynamic for you :)

**Comment by dessant** [comment]
RV works with very few additional item widgets, besides the ones visible in the viewport.
I think your real problem is the time it takes to load the images outside of the viewport, not the instantiation of view classes.

@rafalo1333, you could solve this corner case by loading yourself all the images in the cache at RV init time, so the cache is used when the user scrolls, rather than lazy loading the images.

If you don't want to do manual caching, use AsyncImage as your view class, in that case even if the image did not load yet, the scrolling should be smooth.

**Comment by tito** [comment]
@dessant Low end device wont help even with AsyncImage. At some point, you need to load asset, and it take times. It will be always more visible with low-end device if you don't do precaching.

I just don't want to change RV to make it non-dynamic, as we have already good patterns that work for this case specifically.

**Comment by dessant** [comment]
@tito i agree that this is not something we should do in RV.
